-- Lifecycle notifications commit with the state change. No heartbeats or raw logs.
CREATE TRIGGER stream_builds_insert AFTER INSERT ON builds BEGIN
 INSERT INTO events(id,type,payload_json,correlation_id,wall_time_us) VALUES(lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-a'||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6))),'build.state',json_object('build',NEW.id,'state',NEW.state,'source',(SELECT source_snapshot_id FROM build_plans WHERE id=NEW.plan_id),'branch',(SELECT json_extract(candidate_json,'$.output.name') FROM build_plans WHERE id=NEW.plan_id)),NEW.id,CAST((julianday('now')-2440587.5)*86400000000 AS INTEGER));
END;
CREATE TRIGGER stream_builds_state AFTER UPDATE OF state ON builds WHEN OLD.state != NEW.state BEGIN
 INSERT INTO events(id,type,payload_json,correlation_id,wall_time_us) VALUES(lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-a'||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6))),'build.state',json_object('build',NEW.id,'state',NEW.state,'source',(SELECT source_snapshot_id FROM build_plans WHERE id=NEW.plan_id),'branch',(SELECT json_extract(candidate_json,'$.output.name') FROM build_plans WHERE id=NEW.plan_id)),NEW.id,CAST((julianday('now')-2440587.5)*86400000000 AS INTEGER));
END;
CREATE TRIGGER stream_jobs_insert AFTER INSERT ON jobs BEGIN
 INSERT INTO events(id,type,payload_json,correlation_id,wall_time_us) VALUES(lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-a'||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6))),'job.state',json_object('job',NEW.id,'state',NEW.state,'source',(SELECT source_snapshot_id FROM build_plans WHERE id=(SELECT plan_id FROM builds WHERE id=NEW.build_id)),'branch',(SELECT json_extract(candidate_json,'$.output.name') FROM build_plans WHERE id=(SELECT plan_id FROM builds WHERE id=NEW.build_id))),NEW.build_id,CAST((julianday('now')-2440587.5)*86400000000 AS INTEGER));
END;
CREATE TRIGGER stream_jobs_state AFTER UPDATE OF state ON jobs WHEN OLD.state != NEW.state BEGIN
 INSERT INTO events(id,type,payload_json,correlation_id,wall_time_us) VALUES(lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-a'||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6))),'job.state',json_object('job',NEW.id,'state',NEW.state,'source',(SELECT source_snapshot_id FROM build_plans WHERE id=(SELECT plan_id FROM builds WHERE id=NEW.build_id)),'branch',(SELECT json_extract(candidate_json,'$.output.name') FROM build_plans WHERE id=(SELECT plan_id FROM builds WHERE id=NEW.build_id))),NEW.build_id,CAST((julianday('now')-2440587.5)*86400000000 AS INTEGER));
END;
CREATE TRIGGER stream_attempts_insert AFTER INSERT ON attempts BEGIN
 INSERT INTO events(id,type,payload_json,correlation_id,wall_time_us) VALUES(lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-a'||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6))),'attempt.state',json_object('attempt',NEW.id,'state',NEW.state,'source',(SELECT source_snapshot_id FROM build_plans WHERE id=(SELECT b.plan_id FROM builds b JOIN jobs j ON b.id=j.build_id WHERE j.id=NEW.job_id)),'branch',(SELECT json_extract(candidate_json,'$.output.name') FROM build_plans WHERE id=(SELECT b.plan_id FROM builds b JOIN jobs j ON b.id=j.build_id WHERE j.id=NEW.job_id))),(SELECT build_id FROM jobs WHERE id=NEW.job_id),CAST((julianday('now')-2440587.5)*86400000000 AS INTEGER));
END;
CREATE TRIGGER stream_attempts_state AFTER UPDATE OF state ON attempts WHEN OLD.state != NEW.state BEGIN
 INSERT INTO events(id,type,payload_json,correlation_id,wall_time_us) VALUES(lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-a'||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6))),'attempt.state',json_object('attempt',NEW.id,'state',NEW.state,'source',(SELECT source_snapshot_id FROM build_plans WHERE id=(SELECT b.plan_id FROM builds b JOIN jobs j ON b.id=j.build_id WHERE j.id=NEW.job_id)),'branch',(SELECT json_extract(candidate_json,'$.output.name') FROM build_plans WHERE id=(SELECT b.plan_id FROM builds b JOIN jobs j ON b.id=j.build_id WHERE j.id=NEW.job_id))),(SELECT build_id FROM jobs WHERE id=NEW.job_id),CAST((julianday('now')-2440587.5)*86400000000 AS INTEGER));
END;
