import type { GraphViewV1 } from "../generated/contracts";
import { rollup, type Visual } from "./view";
import { label } from "./model";
export interface ExportOptions {
  labels: boolean;
  metadata: boolean;
  notes: boolean;
}
/** Encode only generated bytes, compatible with the coordinator's restrictive image CSP. */
export function exportDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () =>
      typeof reader.result === "string"
        ? resolve(reader.result)
        : reject(new Error("Export encoding failed."));
    reader.onerror = () => reject(new Error("Export encoding failed."));
    reader.readAsDataURL(blob);
  });
}
const escape = (value: string): string =>
  value.replace(
    /[&<>"']/gu,
    (c) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&apos;",
      })[c] ?? c,
  );
/** Build from selected public model fields, never DOM, external images or page screenshots. */
export function exportJson(
  view: GraphViewV1,
  visual: Visual,
  options: ExportOptions,
): string {
  return JSON.stringify(
    {
      format_version: 1,
      datasets: view.datasets,
      groups: view.groups.map((g) => ({
        ...g,
        name: options.labels ? g.name : "",
      })),
      annotations: options.notes ? view.annotations : [],
      viewport: view.viewport,
      colour: view.colour,
      edges: visual.edges
        .filter(
          (e) =>
            visual.nodes.some((n) => n.identity === e.parent) &&
            visual.nodes.some((n) => n.identity === e.consumer),
        )
        .map((e) => ({ parent: e.parent, consumer: e.consumer })),
      ...(options.labels
        ? {
            labels: visual.nodes.map((n) => ({
              identity: n.identity,
              label: label(n),
            })),
          }
        : {}),
      ...(options.metadata
        ? {
            view_id: view.id,
            revision: view.revision,
            name: view.name,
            description: view.description,
            selector: view.selector,
            filters: view.filters,
            nodes: visual.nodes,
          }
        : {}),
    },
    null,
    2,
  );
}
export function exportSvg(
  view: GraphViewV1,
  visual: Visual,
  options: ExportOptions,
): string {
  const hidden = new Map(
    view.groups
      .filter((g) => g.collapsed)
      .flatMap((g) => g.members.map((id) => [id, g.id] as const)),
  );
  const palette: Record<string, string> = {
    polars_transform: "#dcefe2",
    sql_transform: "#dfe7ff",
    external: "#f6e4ce",
    dataset: "#d9eef1",
    published: "#dcefe2",
    missing: "#f4e6cf",
    unknown: "#e8eaee",
  };
  const boxes = visual.nodes
    .filter((n) => !hidden.has(n.identity))
    .map((n) => ({
      id: n.identity,
      position: visual.positions[n.identity] ?? { x: 0, y: 0 },
      name: label(n),
      lines: [label(n)],
      width: 260,
      height: 48,
      note: false,
      fill:
        palette[view.colour === "resource" ? n.resource_type : n.publication] ??
        "#e8eaee",
      dashed: n.publication === "missing",
    }));
  boxes.push(
    ...view.groups
      .filter((g) => g.collapsed)
      .map((g) => ({
        id: g.id,
        position: g.position,
        name: g.name,
        lines: [g.name, ...(rollup(g, visual.nodes).match(/.{1,36}/gu) ?? [])],
        width: 280,
        height: 80,
        note: false,
        fill: "#eaf4f1",
        dashed: false,
      })),
  );
  if (options.notes)
    boxes.push(
      ...view.annotations.map((n) => ({
        id: n.id,
        position: n.position,
        name: n.text,
        lines: n.text
          .split("\n")
          .flatMap((line) => line.match(/.{1,38}/gu) ?? [""]),
        width: 280,
        height:
          24 +
          16 *
            n.text
              .split("\n")
              .flatMap((line) => line.match(/.{1,38}/gu) ?? [""]).length,
        note: true,
        fill: "#fff6ce",
        dashed: false,
      })),
    );
  const minX = Math.min(0, ...boxes.map((b) => b.position.x)) - 60,
    minY = Math.min(0, ...boxes.map((b) => b.position.y)) - 60;
  const width =
      Math.max(300, ...boxes.map((b) => b.position.x + b.width)) - minX + 20,
    height =
      Math.max(100, ...boxes.map((b) => b.position.y + b.height)) - minY + 20;
  let body = "";
  for (const group of view.groups.filter((g) => !g.collapsed)) {
    const members = boxes.filter((b) => group.members.includes(b.id));
    if (!members.length) continue;
    const x = Math.min(...members.map((b) => b.position.x)) - 16,
      y = Math.min(...members.map((b) => b.position.y)) - 52,
      w = Math.max(...members.map((b) => b.position.x + b.width)) + 16 - x,
      h = Math.max(...members.map((b) => b.position.y + b.height)) + 16 - y;
    body += `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="6" fill="#eef2f6" stroke="#aab5c2"/>`;
    if (options.labels)
      body += `<text x="${x + 8}" y="${y + 22}" font-family="sans-serif" font-size="12">${escape(group.name)}</text>`;
  }
  for (const edge of visual.edges) {
    const a = boxes.find(
        (b) => b.id === (hidden.get(edge.parent) ?? edge.parent),
      ),
      b = boxes.find(
        (b) => b.id === (hidden.get(edge.consumer) ?? edge.consumer),
      );
    if (a && b && a !== b)
      body += `<path d="M ${a.position.x + a.width} ${a.position.y + 24} L ${b.position.x} ${b.position.y + 24}" stroke="#607080" fill="none" marker-end="url(#arrow)"/>`;
  }
  for (const box of boxes) {
    body += `<rect x="${box.position.x}" y="${box.position.y}" width="${box.width}" height="${box.height}" rx="4" fill="${box.fill}" stroke="#607080"${box.dashed ? ' stroke-dasharray="4 4"' : ""}/>`;
    if (options.labels || (options.notes && box.note))
      body += `<text x="${box.position.x + 8}" y="${box.position.y + 24}" font-family="sans-serif" font-size="12">${box.lines.map((line, index) => `<tspan x="${box.position.x + 8}" dy="${index ? 16 : 0}">${escape(line)}</tspan>`).join("")}</text>`;
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minX} ${minY} ${width} ${height}" width="${width}" height="${height}"><defs><marker id="arrow" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#607080"/></marker></defs>${options.metadata ? `<metadata>${escape(exportJson(view, visual, options))}</metadata>` : ""}${body}</svg>`;
}
export async function createExport(
  format: "json" | "svg" | "png",
  view: GraphViewV1,
  visual: Visual,
  options: ExportOptions,
): Promise<Blob> {
  let blob: Blob;
  if (format === "json")
    blob = new Blob([exportJson(view, visual, options)], {
      type: "application/json",
    });
  else {
    const svg = exportSvg(view, visual, options);
    blob = new Blob([svg], { type: "image/svg+xml" });
    if (format === "png") {
      const url = await exportDataUrl(blob);
      const image = new Image();
      image.src = url;
      await image.decode();
      const scale = Math.min(1, 4096 / image.width, 4096 / image.height);
      const canvas = document.createElement("canvas");
      canvas.width = Math.max(1, Math.round(image.width * scale));
      canvas.height = Math.max(1, Math.round(image.height * scale));
      const context = canvas.getContext("2d");
      if (!context) throw new Error("PNG rendering is unavailable.");
      context.drawImage(image, 0, 0, canvas.width, canvas.height);
      blob = await new Promise<Blob>((resolve, reject) =>
        canvas.toBlob(
          (b) => (b ? resolve(b) : reject(new Error("PNG export failed."))),
          "image/png",
        ),
      );
    }
  }
  return blob;
}
