import type { GraphViewV1 } from "../generated/contracts";
import { type Visual } from "./view";
import { label } from "./model";
import { paint } from "./overlays";
export interface ExportOptions {
  labels: boolean;
  metadata: boolean;
}
/** Encode only generated bytes, compatible with the coordinator's restrictive image CSP. */
export function exportDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () =>
      typeof reader.result === "string"
        ? resolve(reader.result)
        : reject(new Error("Export encoding failed."));
    reader.onerror = () => reject(new Error("Export encoding failed."));
    reader.readAsDataURL(blob);
  });
}
const escape = (value: string): string =>
  value.replace(
    /[&<>"']/gu,
    (c) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&apos;",
      })[c] ?? c,
  );
/** Build from selected public model fields, never DOM, external images or page screenshots. */
export function exportJson(
  view: GraphViewV1,
  visual: Visual,
  options: ExportOptions,
): string {
  return JSON.stringify(
    {
      format_version: 1,
      datasets: view.datasets,
      colour: view.colour,
      edges: visual.edges
        .filter(
          (e) =>
            visual.nodes.some((n) => n.identity === e.parent) &&
            visual.nodes.some((n) => n.identity === e.consumer),
        )
        .map((e) => ({ parent: e.parent, consumer: e.consumer })),
      ...(options.labels
        ? {
            labels: visual.nodes.map((n) => ({
              identity: n.identity,
              label: label(n),
            })),
          }
        : {}),
      ...(options.metadata
        ? {
            view_id: view.id,
            revision: view.revision,
            name: view.name,
            description: view.description,
            selector: view.selector,
            nodes: visual.nodes,
          }
        : {}),
    },
    null,
    2,
  );
}
export function exportSvg(
  view: GraphViewV1,
  visual: Visual,
  options: ExportOptions,
): string {
  const palette: Record<string, string> = {
    polars_transform: "#dcefe2",
    sql_transform: "#dfe7ff",
    external: "#f6e4ce",
    dataset: "#d9eef1",
    published: "#dcefe2",
    missing: "#f4e6cf",
    unknown: "#e8eaee",
    source: "#d5e9fb",
    imported: "#e8d9f7",
    pandas_transform: "#e8d9f7",
    zero: "#e5e7eb",
    NoChecks: "#e5e7eb",
    Unavailable: "#e5e7eb",
    Canceled: "#e5e7eb",
    Interrupted: "#e5e7eb",
    bin0: "#d7eee0",
    Succeeded: "#d7eee0",
    Passed: "#d7eee0",
    current: "#d7eee0",
    bin1: "#c5ddf5",
    Running: "#c5ddf5",
    target: "#c5ddf5",
    planned: "#c5ddf5",
    bin2: "#f7dfb5",
    Warning: "#f7dfb5",
    data: "#f7dfb5",
    ancestor: "#f7dfb5",
    trigger: "#f7dfb5",
    bin3: "#f5c9cc",
    Failed: "#f5c9cc",
    logic: "#f5c9cc",
    excluded: "#f5c9cc",
    never_built: "#e6d9f3",
    boundary: "#e6d9f3",
    cached: "#e6d9f3",
  };
  const boxes = visual.nodes.map((n) => ({
    id: n.identity,
    position: visual.positions[n.identity] ?? { x: 0, y: 0 },
    name: label(n),
    lines: [label(n)],
    width: 260,
    height: 48,
    fill: palette[paint(n, view.colour).key] ?? "#e8eaee",
    dashed: n.publication === "missing",
  }));
  const minX = Math.min(0, ...boxes.map((b) => b.position.x)) - 60,
    minY = Math.min(0, ...boxes.map((b) => b.position.y)) - 60;
  const width =
      Math.max(300, ...boxes.map((b) => b.position.x + b.width)) - minX + 20,
    height =
      Math.max(100, ...boxes.map((b) => b.position.y + b.height)) - minY + 20;
  let body = "";
  for (const edge of visual.edges) {
    const a = boxes.find((b) => b.id === edge.parent),
      b = boxes.find((b) => b.id === edge.consumer);
    if (a && b && a !== b)
      body += `<path d="M ${a.position.x + a.width} ${a.position.y + 24} L ${b.position.x} ${b.position.y + 24}" stroke="#607080" fill="none" marker-end="url(#arrow)"/>`;
  }
  for (const box of boxes) {
    body += `<rect x="${box.position.x}" y="${box.position.y}" width="${box.width}" height="${box.height}" rx="4" fill="${box.fill}" stroke="#607080"${box.dashed ? ' stroke-dasharray="4 4"' : ""}/>`;
    if (options.labels)
      body += `<text x="${box.position.x + 8}" y="${box.position.y + 24}" font-family="sans-serif" font-size="12">${box.lines.map((line, index) => `<tspan x="${box.position.x + 8}" dy="${index ? 16 : 0}">${escape(line)}</tspan>`).join("")}</text>`;
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minX} ${minY} ${width} ${height}" width="${width}" height="${height}"><defs><marker id="arrow" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#607080"/></marker></defs>${options.metadata ? `<metadata>${escape(exportJson(view, visual, options))}</metadata>` : ""}${body}</svg>`;
}
export async function createExport(
  format: "json" | "svg" | "png",
  view: GraphViewV1,
  visual: Visual,
  options: ExportOptions,
): Promise<Blob> {
  let blob: Blob;
  if (format === "json")
    blob = new Blob([exportJson(view, visual, options)], {
      type: "application/json",
    });
  else {
    const svg = exportSvg(view, visual, options);
    blob = new Blob([svg], { type: "image/svg+xml" });
    if (format === "png") {
      const url = await exportDataUrl(blob);
      const image = new Image();
      image.src = url;
      await image.decode();
      const scale = Math.min(1, 4096 / image.width, 4096 / image.height);
      const canvas = document.createElement("canvas");
      canvas.width = Math.max(1, Math.round(image.width * scale));
      canvas.height = Math.max(1, Math.round(image.height * scale));
      const context = canvas.getContext("2d");
      if (!context) throw new Error("PNG rendering is unavailable.");
      context.drawImage(image, 0, 0, canvas.width, canvas.height);
      blob = await new Promise<Blob>((resolve, reject) =>
        canvas.toBlob(
          (b) => (b ? resolve(b) : reject(new Error("PNG export failed."))),
          "image/png",
        ),
      );
    }
  }
  return blob;
}
