"""Deterministic contract exports from tf-protocol's authored schema (stdlib only)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def typescript(node):
    if "$ref" in node:
        return node["$ref"].removeprefix("#/$defs/")
    if "oneOf" in node:
        return "(" + " | ".join(typescript(branch) for branch in node["oneOf"]) + ")"
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return "(" + " | ".join(json.dumps(v) for v in node["enum"]) + ")"
    kind = node["type"]
    if kind in ("integer", "number"):
        return "number"
    if kind in ("boolean", "string", "null"):
        return kind
    if kind == "array":
        return "ReadonlyArray<" + typescript(node["items"]) + ">"
    if kind == "object":
        if isinstance(node.get("additionalProperties"), dict):
            # Index signatures support recursive JSON aliases; Record aliases do not.
            return "{ readonly [key: string]: " + typescript(node["additionalProperties"]) + " }"
        required = node.get("required", [])
        fields = [
            "readonly " + json.dumps(key) + ("" if key in required else "?") + ": " + typescript(value)
            for key, value in node.get("properties", {}).items()
        ]
        return "{ " + "; ".join(fields) + " }"
    raise ValueError("Unsupported schema type: " + kind)


def write(relative, text):
    path = ROOT / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main():
    source = json.loads((ROOT / "schemas/contracts-v1.schema.json").read_text())
    versions = json.loads((ROOT / "schemas/versions.json").read_text())
    exported = {**source, "$id": "urn:transflow:worker-control:v1", "$ref": "#/$defs/ControlFrameV1"}
    write("schemas/generated/worker-control-v1.schema.json", json.dumps(exported, indent=2) + "\n")
    cli = {**source, "$id": "urn:transflow:cli-result:v1", "$ref": "#/$defs/CliEnvelopeV1"}
    write("schemas/generated/cli-result-v1.schema.json", json.dumps(cli, indent=2) + "\n")
    ts = "// Generated by tools/contracts/generate.py. Do not edit.\n"
    for name, definition in source["$defs"].items():
        ts += "// prettier-ignore\nexport type " + name + " = " + typescript(definition) + ";\n\n"
    write("web/src/generated/contracts.ts", ts.rstrip() + "\n")
    # Embedded JSON remains data; it is not executable schema interpolation.
    schema_text = json.dumps(source, separators=(",", ":"))
    py = '"""Generated contract data; edit schemas/ and rerun the generator."""\n\n'
    py += "# fmt: off\n# ruff: noqa: E501\n"
    py += "SCHEMA_TEXT = " + repr(schema_text) + "\n"
    py += "PROTOCOL_MAJOR = " + str(versions["worker_protocol"]["major"]) + "\n"
    py += "PROTOCOL_MINOR = " + str(versions["worker_protocol"]["minor"]) + "\n"
    write("python/worker/src/transflow_worker/_wire_schema.py", py)
    validators = '"""Generated named validators backed by the shared runtime assertion engine."""\n\n'
    validators += "from .wire import validate_document\n\n"
    for name in source["$defs"]:
        validators += '\ndef validate_' + name + '(value: object) -> None:\n'
        validators += '    """Assert the ' + name + ' contract, including custom formats."""\n'
        validators += '    validate_document("' + name + '", value)\n\n'
    write("python/worker/src/transflow_worker/_wire_validators.py", validators.rstrip() + "\n")


if __name__ == "__main__":
    main()
